name: Build Signed Release APK SaeShop

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write  # Grant write permissions to allow push

jobs:
  build:
    name: Build and Sign Android Release APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Docker Image with Android SDK and Tools
      run: |
        docker run --rm \
          -v $PWD:/workspace \
          -w /workspace \
          ghcr.io/andrewmcodes/android-tools:latest \
          bash -c "
          ./gradlew assembleRelease &&
          echo '${{ secrets.KEYSTORE_FILE_BASE64 }}' | base64 --decode > keystore.jks &&
          jarsigner \
            -verbose \
            -keystore keystore.jks \
            -storepass '${{ secrets.KEYSTORE_PASSWORD }}' \
            -keypass '${{ secrets.KEYSTORE_KEY_PASSWORD }}' \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            '${{ secrets.KEYSTORE_ALIAS }}' &&
          zipalign -v -p 4 \
            app/build/outputs/apk/release/app-release-unsigned.apk \
            app/build/outputs/apk/release/app-release-signed-aligned.apk
          "

    - name: Move APK to apk/ directory
      run: |
        mkdir -p apk
        mv app/build/outputs/apk/release/app-release-signed-aligned.apk apk/

    - name: Commit APK to repository
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add apk/
        git commit -m "Add Signed and Aligned APK [skip ci]"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
